"""01_models.

Revision ID: 17da326cb886
Revises:
Create Date: 2024-06-23 23:36:21.266531
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '17da326cb886'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'context',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_name'), ['name'], unique=True)

    op.create_table(
        'source',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('context_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('hash', sa.String(), nullable=False),
        sa.Column('vector_hex', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['context_id'], ['context.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_created'), ['created'], unique=False)

    op.create_table(
        'blob',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('blob_index', sa.Integer(), nullable=False),
        sa.Column('vector_hex', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('blob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blob_created'), ['created'], unique=False)

    op.create_table(
        'link',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('blob_id', sa.Integer(), nullable=False),
        sa.Column('target_source_id', sa.Integer(), nullable=False),
        sa.Column('origin_distance', sa.Float(), nullable=False),
        sa.Column('destination_distance', sa.Float(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['blob_id'], ['blob.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_source_id'], ['source.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_created'))

    op.drop_table('link')
    with op.batch_alter_table('blob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blob_created'))

    op.drop_table('blob')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_created'))

    op.drop_table('source')
    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_name'))
        batch_op.drop_index(batch_op.f('ix_context_created'))

    op.drop_table('context')
    # ### end Alembic commands ###
