"""02_links.

Revision ID: e8cf3b400e20
Revises: 7bf1833a7094
Create Date: 2024-06-23 00:02:57.700529
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8cf3b400e20'
down_revision: str | None = '7bf1833a7094'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'link',
        sa.Column('blob_id', sa.Integer(), nullable=False),
        sa.Column('target_source_id', sa.Integer(), nullable=False),
        sa.Column('origin_distance', sa.Float(), nullable=False),
        sa.Column('destination_distance', sa.Float(), nullable=False),
        sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['blob_id'], ['blob.id']),
        sa.ForeignKeyConstraint(['target_source_id'], ['source.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_created'), ['created'], unique=False)

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_hex', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('vector_hex')

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_created'))

    op.drop_table('link')
    # ### end Alembic commands ###
